redis_url: "redis://localhost:6379/0"
allowed_origins: "http://localhost:3000"
sqs_thread_ids_queue_url: ~
sqs_reports_queue_url: ~
thread_list_worker_threads_per_message: 500
thread_batch_worker_poll_interval: 30
thread_batch_worker_lock_ttl: 900
thread_batch_worker_max_messages_per_run: 5
spreadsheet_sync_worker_poll_interval: 30
spreadsheet_sync_worker_lock_ttl: 300
thread_batch_fetcher_batch_size: 20
thread_batch_fetcher_inter_batch_sleep: 1
thread_list_worker_thread_id_limit: 6000
