version: 2

updates:
  - package-ecosystem: "bundler"
    directory: "/apps/api"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/apps/api"
    schedule:
      interval: "weekly"

  - package-ecosystem: "terraform"
    directory: "/terraform/environments/dev"
    schedule:
      interval: "weekly"

  - package-ecosystem: "terraform"
    directory: "/terraform/environments/prod"
    schedule:
      interval: "weekly"

  - package-ecosystem: "terraform"
    directory: "/terraform/environments/management"
    schedule:
      interval: "weekly"
