redis_url: <%= ENV['REDIS_URL'] %>
allowed_origins: <%= ENV['ALLOWED_ORIGINS'] %>
sqs_thread_ids_queue_url: <%= ENV['SQS_THREAD_IDS_QUEUE_URL'] %>
sqs_reports_queue_url: <%= ENV['SQS_REPORTS_QUEUE_URL'] %>
thread_list_worker_threads_per_message: <%= ENV.fetch('THREAD_LIST_WORKER_THREADS_PER_MESSAGE', '500').to_i %>
thread_batch_worker_poll_interval: <%= ENV.fetch('THREAD_BATCH_WORKER_POLL_INTERVAL', '30').to_i %>
thread_batch_worker_lock_ttl: <%= ENV.fetch('THREAD_BATCH_WORKER_LOCK_TTL', '900').to_i %>
thread_batch_worker_max_messages_per_run: <%= ENV.fetch('THREAD_BATCH_WORKER_MAX_MESSAGES_PER_RUN', '3').to_i %>
spreadsheet_sync_worker_poll_interval: <%= ENV.fetch('SPREADSHEET_SYNC_WORKER_POLL_INTERVAL', '30').to_i %>
spreadsheet_sync_worker_lock_ttl: <%= ENV.fetch('SPREADSHEET_SYNC_WORKER_LOCK_TTL', '300').to_i %>
thread_batch_fetcher_batch_size: <%= ENV.fetch('THREAD_BATCH_FETCHER_BATCH_SIZE', '20').to_i %>
thread_batch_fetcher_inter_batch_sleep: <%= ENV.fetch('THREAD_BATCH_FETCHER_INTER_BATCH_SLEEP', '0.5').to_f %>
thread_list_worker_thread_id_limit: <%= ENV.fetch('THREAD_LIST_WORKER_THREAD_ID_LIMIT', '6000').to_i %>
spreadsheet_sync_worker_max_messages_per_run: <%= ENV.fetch('SPREADSHEET_SYNC_WORKER_MAX_MESSAGES_PER_RUN', '3').to_i %>
sync_min_interval: <%= ENV.fetch('SYNC_MIN_INTERVAL', '300').to_i %>
rate_limit_global_limit: <%= ENV.fetch('RATE_LIMIT_GLOBAL_LIMIT', '1000').to_i %>
rate_limit_global_period: <%= ENV.fetch('RATE_LIMIT_GLOBAL_PERIOD', '300').to_i %>
rate_limit_auth_limit: <%= ENV.fetch('RATE_LIMIT_AUTH_LIMIT', '30').to_i %>
rate_limit_auth_period: <%= ENV.fetch('RATE_LIMIT_AUTH_PERIOD', '300').to_i %>
