source "https://rubygems.org"

ruby "3.4.4"

# Bundle edge Rails instead: gem "rails", github: "rails/rails", branch: "main"
gem "rails", "~> 8.0.3"
# Use the Puma web server [https://github.com/puma/puma]
gem "puma", ">= 5.0"

# Use Rack CORS for handling Cross-Origin Resource Sharing (CORS), making cross-origin Ajax possible
gem "rack-cors"

# JWT for stateless authentication
gem "jwt"

# Google OAuth2 authentication
gem "omniauth-google-oauth2"
gem "omniauth-rails_csrf_protection"

group :development, :test do
  # See https://guides.rubyonrails.org/debugging_rails_applications.html#debugging-with-the-debug-gem
  gem "debug", platforms: %i[ mri windows ], require: "debug/prelude"
  # RSpec testing framework for Rails
  gem "rspec-rails", "~> 7.1"
  # Automatically generate descriptions for RSpec request specs
  gem "rspec-request_describer"
end
